In [1]:
import tensorflow as tf
import os
import numpy as np
from tensorflow import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [2]:
#load trained model
model = tf.keras.models.load_model('models/brain_model_finetune.h5')

In [3]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 vgg16 (Functional)          (None, 7, 7, 512)         14714688  
                                                                 
 conv2d (Conv2D)             (None, 5, 5, 32)          147488    
                                                                 
 dropout (Dropout)           (None, 5, 5, 32)          0         
                                                                 
 global_average_pooling2d (G  (None, 32)               0         
 lobalAveragePooling2D)                                          
                                                                 
 dense (Dense)               (None, 4)                 132       
                                                                 
Total params: 14,862,308
Trainable params: 7,227,044
Non-trainable params: 7,635,264
_____________________________________

In [4]:
base_dir = "input"
test_dir = os.path.join(base_dir, 'Testing')

In [5]:
(IMG_HEIGHT,IMG_WIDTH) = (224,224)
batch_size = 160

In [6]:
#testing data as batches of tensor image data
test_image_generator = ImageDataGenerator(rescale=1./255)

In [7]:
test_data_generator = test_image_generator.flow_from_directory(
    directory = test_dir,
    target_size = (IMG_HEIGHT,IMG_WIDTH),
    batch_size = batch_size,
    class_mode = "categorical"
)

Found 256 images belonging to 4 classes.


In [8]:
labels = test_data_generator.class_indices
print(labels)

{'Mild_Demented': 0, 'Moderate_Demented': 1, 'Non_Demented': 2, 'Very_Mild_Demented': 3}


In [9]:
# Learn about dataset labels

dataset_labels = sorted(test_data_generator.class_indices.items())
dataset_labels = np.array([key.title() for key, value in dataset_labels])
print(dataset_labels)

['Mild_Demented' 'Moderate_Demented' 'Non_Demented' 'Very_Mild_Demented']


In [10]:
#check the shape
test_image_batch, test_label_batch = next(iter(test_data_generator))
true_label_ids = np.argmax(test_label_batch, axis=-1)

print("test batch shape:", test_image_batch.shape)

test batch shape: (160, 224, 224, 3)


In [11]:
test_image_batch[0].shape

(224, 224, 3)

In [12]:
# predict probabilities for test set
yhat_probs = model.predict(test_image_batch)

5/5 [==============================] - 20s 4s/step


In [13]:
yhat_probs[0]

array([0.25054157, 0.00090766, 0.28742728, 0.46112344], dtype=float32)

In [14]:
yhat_classes=[]
for i in yhat_probs:
    data=i.tolist()
   
    maxvalue=data.index(max(data))
   
    yhat_classes.append(maxvalue)
yhat_classes

[3,
 2,
 3,
 3,
 3,
 2,
 0,
 1,
 0,
 0,
 3,
 0,
 0,
 2,
 0,
 0,
 2,
 0,
 0,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 2,
 0,
 0,
 2,
 3,
 0,
 3,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 2,
 3,
 1,
 1,
 0,
 1,
 3,
 1,
 2,
 3,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 3,
 0,
 1,
 0,
 1,
 3,
 2,
 1,
 1,
 2,
 0,
 1,
 0,
 2,
 1,
 2,
 1,
 3,
 3,
 0,
 0,
 1,
 3,
 1,
 3,
 3,
 0,
 1,
 3,
 3,
 1,
 3,
 3,
 1,
 0,
 2,
 0,
 1,
 1,
 3,
 3,
 1,
 1,
 0,
 0,
 1,
 3,
 3,
 3,
 1,
 1,
 3,
 2,
 1,
 2,
 3,
 2,
 1,
 1,
 2,
 0,
 1,
 2,
 3,
 3,
 2,
 0,
 3,
 2,
 0,
 0,
 0,
 3,
 0,
 3,
 0,
 0,
 1,
 3,
 3,
 1,
 0,
 0,
 0,
 1,
 3,
 3,
 3,
 0,
 2,
 1,
 2,
 0,
 0,
 3,
 3,
 2,
 1,
 1]

In [15]:
yhat_probs

array([[2.50541568e-01, 9.07661219e-04, 2.87427276e-01, 4.61123437e-01],
       [8.36458877e-02, 7.65724224e-04, 5.49912572e-01, 3.65675807e-01],
       [3.22536707e-01, 1.07199140e-02, 1.79436460e-01, 4.87306952e-01],
       [7.39671886e-02, 2.59010517e-03, 1.66395843e-01, 7.57046878e-01],
       [4.68177646e-02, 1.73299995e-04, 1.09656408e-01, 8.43352497e-01],
       [3.03973481e-02, 7.30793909e-05, 7.93426752e-01, 1.76102877e-01],
       [8.04471672e-01, 1.00630475e-03, 1.09024890e-01, 8.54972228e-02],
       [2.66795792e-06, 9.99993086e-01, 9.90935291e-07, 3.25917267e-06],
       [8.88339937e-01, 4.14205622e-03, 3.42298448e-02, 7.32881650e-02],
       [7.36455560e-01, 3.92440427e-03, 8.67251009e-02, 1.72894880e-01],
       [1.34746924e-01, 1.47965108e-03, 1.65911064e-01, 6.97862387e-01],
       [9.19174492e-01, 7.40506293e-05, 4.01220918e-02, 4.06293049e-02],
       [6.62759483e-01, 9.40976242e-05, 1.90354779e-01, 1.46791652e-01],
       [7.81223690e-03, 2.60772722e-05, 5.37588418e

In [16]:
#convert numeric classes to real name class
pred_class = np.array(list(list(labels.keys())[list(labels.values()).index(i)] for i in yhat_classes))
pred_class

array(['Very_Mild_Demented', 'Non_Demented', 'Very_Mild_Demented',
       'Very_Mild_Demented', 'Very_Mild_Demented', 'Non_Demented',
       'Mild_Demented', 'Moderate_Demented', 'Mild_Demented',
       'Mild_Demented', 'Very_Mild_Demented', 'Mild_Demented',
       'Mild_Demented', 'Non_Demented', 'Mild_Demented', 'Mild_Demented',
       'Non_Demented', 'Mild_Demented', 'Mild_Demented',
       'Moderate_Demented', 'Moderate_Demented', 'Very_Mild_Demented',
       'Moderate_Demented', 'Moderate_Demented', 'Moderate_Demented',
       'Moderate_Demented', 'Moderate_Demented', 'Non_Demented',
       'Mild_Demented', 'Mild_Demented', 'Non_Demented',
       'Very_Mild_Demented', 'Mild_Demented', 'Very_Mild_Demented',
       'Mild_Demented', 'Mild_Demented', 'Moderate_Demented',
       'Mild_Demented', 'Moderate_Demented', 'Mild_Demented',
       'Mild_Demented', 'Non_Demented', 'Very_Mild_Demented',
       'Moderate_Demented', 'Moderate_Demented', 'Mild_Demented',
       'Moderate_Demented',

In [17]:
#calculating metrics for a neural network model using sklearn
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

In [18]:
testy = np.array([np.where(r==1)[0][0] for r in test_label_batch])
testy

array([3, 2, 3, 3, 3, 2, 0, 1, 0, 0, 3, 0, 0, 3, 0, 0, 2, 0, 0, 1, 1, 3,
       1, 1, 1, 1, 1, 2, 2, 0, 2, 3, 2, 2, 0, 0, 1, 0, 1, 0, 2, 2, 3, 1,
       1, 0, 1, 3, 1, 2, 3, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 3, 0, 1, 0, 1,
       3, 2, 1, 1, 2, 0, 1, 0, 2, 1, 2, 1, 2, 3, 0, 0, 1, 3, 1, 3, 3, 0,
       1, 3, 3, 1, 3, 3, 1, 0, 2, 0, 1, 1, 3, 3, 1, 1, 0, 0, 1, 3, 3, 3,
       1, 1, 3, 2, 1, 2, 2, 2, 1, 1, 2, 2, 1, 2, 3, 3, 2, 0, 3, 2, 0, 0,
       0, 3, 0, 3, 0, 0, 1, 3, 3, 1, 0, 0, 0, 1, 3, 3, 3, 3, 2, 1, 2, 0,
       0, 3, 2, 2, 1, 1], dtype=int64)

In [19]:
test_real = np.array(list(list(labels.keys())[list(labels.values()).index(i)] for i in testy))
test_real

array(['Very_Mild_Demented', 'Non_Demented', 'Very_Mild_Demented',
       'Very_Mild_Demented', 'Very_Mild_Demented', 'Non_Demented',
       'Mild_Demented', 'Moderate_Demented', 'Mild_Demented',
       'Mild_Demented', 'Very_Mild_Demented', 'Mild_Demented',
       'Mild_Demented', 'Very_Mild_Demented', 'Mild_Demented',
       'Mild_Demented', 'Non_Demented', 'Mild_Demented', 'Mild_Demented',
       'Moderate_Demented', 'Moderate_Demented', 'Very_Mild_Demented',
       'Moderate_Demented', 'Moderate_Demented', 'Moderate_Demented',
       'Moderate_Demented', 'Moderate_Demented', 'Non_Demented',
       'Non_Demented', 'Mild_Demented', 'Non_Demented',
       'Very_Mild_Demented', 'Non_Demented', 'Non_Demented',
       'Mild_Demented', 'Mild_Demented', 'Moderate_Demented',
       'Mild_Demented', 'Moderate_Demented', 'Mild_Demented',
       'Non_Demented', 'Non_Demented', 'Very_Mild_Demented',
       'Moderate_Demented', 'Moderate_Demented', 'Mild_Demented',
       'Moderate_Demented', 'V

In [20]:
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(testy, yhat_classes)
print('Accuracy: %f' % accuracy)
# precision tp / (tp + fp)
precision = precision_score(testy, yhat_classes,average='macro')
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(testy, yhat_classes,average='macro')
print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(testy, yhat_classes,average='macro')
print('F1 score: %f' % f1)

Accuracy: 0.937500
Precision: 0.938699
Recall: 0.920513
F1 score: 0.925061


SyntaxError: unexpected character after line continuation character (3806880944.py, line 1)

SyntaxError: unexpected character after line continuation character (282745601.py, line 1)

SyntaxError: unexpected character after line continuation character (2893826588.py, line 1)